### ISSUE TITLE
Descriptors for a set of 1000 compounds on Jupyter Notebook

### ISSUE THREAD

**Issue by RicardoMBorges** [c-martinez/pydescriptors#1]
Hello, 
I’ve just found this and I wonder if I could used it as part od my pipeline. I’m designing a pipeline for a compound database visualization, but I’m using Padel offline. Padel is taking forever to run a set of ~1000 structures.
Could I use your pydescriptors to run it and to add it as part of my pipeline?
Of course all citations are due.
Thanks 
Ricardo

**Comment by c-martinez** [comment]
Hi @RicardoMBorges!

Thank you for reaching out. Of course you are welcome to use it. I've just added an Apache license to this repo so you are free to reuse it. 

If you could cite http://hdl.handle.net/10036/3026, that would be fantastic.
